# Generated by Django 4.0.4 on 2022-04-25 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_topic_topic_topic_str_counts_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteopinion',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
