# Generated by Django 4.0.4 on 2022-04-26 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_topic_pub_date_alter_voteopinion_vote_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteopinion',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='voteopinion',
            name='vote_opinion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
