# Generated by Django 4.0.4 on 2022-04-29 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_voteopinion_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
